name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: |
            rtainjapan/srt-live-server
            ghcr.io/rtainjapan/srt-live-server
          tag-sha: true
      - uses: docker/login-action@v1
        with:
          username: hoishin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hoishin
          password: ${{ secrets.CR_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          build-args: TYPEKIT_ID=${{ secrets.TYPEKIT_ID }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
